# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# DATABASE (MongoDB - ajusta si usas otra)
# ===============================
spring.mongodb.uri=mongodb://localhost:27017/ms_security

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=mi_clave_super_secreta_123456_esta_es_mucho_mas_larga_y_segura_para_jwt_hmac_sha512
jwt.expiration=86400000

# ===============================
# LOGGING (opcional pero útil)
# ===============================
logging.level.org.springframework.security=DEBUG

# ===============================
# SPRING CONFIG
# ===============================
spring.main.allow-circular-references=true

# ===============================
# EMAIL CONFIG (Gmail)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cristianms45144@gmail.com
spring.mail.password=tu_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true