from datetime import date, datetime
from typing import Protocol

from app.weather.domain.entities.weather_notification import WeatherNotification


class IWeatherNotificationRepository(Protocol):
    def create(self, notification: WeatherNotification) -> WeatherNotification: ...

    def update(self, notification: WeatherNotification) -> WeatherNotification: ...

    def get_by_id(self, alert_id: str) -> WeatherNotification | None: ...

    def list_by_user_id(self, user_id: str) -> list[WeatherNotification]: ...

    def deactivate_by_id(self, alert_id: str) -> bool: ...

    def list_due_for_hour(self, current_hour: int, today: date, max_hours_before: int) -> list[WeatherNotification]: ...

    def mark_alert_sent(self, notification_id: str, sent_at: datetime) -> None: ...
