name: MS Security

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'ms-security/**'
      - '.github/workflows/ms-security.yml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'ms-security/**'
      - '.github/workflows/ms-security.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ms-security

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build
        run: ./mvnw -B clean verify
